# action.yml
name: 'ScancodeSQ'
description: 'Scan licenses and copyrights in code'
inputs:
  directory-to-scan:  # id of input
    description: 'Which directory to scan'
    required: false
    default: 'scancode-files'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory-to-scan }}
